name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup Secrets for Application
      env:
        SUPER_SECRET: ${{ secrets.DJANGO_SECRET_KEY }}
      run: |
        sudo echo "SECRET_KEY='$SUPER_SECRET'" > django-project/.env
        sudo chown `whoami` .env
        sudo chmod 400 django-project/mysite/.env
    - name: Run Tests
      run: |
        python django-project/manage.py test
