name: Run packer build on a template file

on:
  push:
    branches:
        - 'master'
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Packer build on AWS
        uses: ExitoLab/packer_build_action_aws@v0.2.10
        with:
          templateFile: 'packer-template.json'
          workingDir: 'ami'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ECR_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ECR_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
          GITHUB_BRANCH: ${{ steps.extract_branch.outputs.branch }}